/**
 * Prisma seed file
 * Run with: npx prisma db seed
 * Pre-loads 5 countries, each with 10 questions about "Violence Is Never The Answer"
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();


const countries = [
  {
    name: "Canada",
    slug: "canada",
    flagEmoji: "🇨🇦",
    monument: "CN Tower, Toronto",
    order: 1,
    questions: [
      {
        text: "According to the text, what is the main message about violence?",
        optionA: "Violence is sometimes necessary to solve conflicts.",
        optionB: "Violence is never the answer to any problem.",
        optionC: "Violence is acceptable in self-defense situations.",
        optionD: "Violence can be a useful tool in certain contexts.",
        correctOption: "B",
        order: 1,
      },
      {
        text: "What does the text suggest we should do instead of using violence?",
        optionA: "Ignore the problem completely.",
        optionB: "Fight back with more force.",
        optionC: "Use words and peaceful dialogue to resolve conflicts.",
        optionD: "Ask someone else to fight for us.",
        correctOption: "C",
        order: 2,
      },
      {
        text: "According to the text, what can violence cause in communities?",
        optionA: "Unity and strength.",
        optionB: "Fear, trauma, and division.",
        optionC: "Respect and admiration.",
        optionD: "Progress and development.",
        correctOption: "B",
        order: 3,
      },
      {
        text: "What role does empathy play in preventing violence, according to the text?",
        optionA: "It has no effect on violence.",
        optionB: "It makes people weaker.",
        optionC: "It helps us understand others' feelings and reduces conflict.",
        optionD: "It encourages people to be more aggressive.",
        correctOption: "C",
        order: 4,
      },
      {
        text: "Which of the following is described as a peaceful way to solve disagreements?",
        optionA: "Shouting and threatening others.",
        optionB: "Walking away and ignoring the issue forever.",
        optionC: "Negotiation and respectful conversation.",
        optionD: "Using physical force to show dominance.",
        correctOption: "C",
        order: 5,
      },
      {
        text: "What does the text say about the consequences of violence for the person who commits it?",
        optionA: "They gain power and respect.",
        optionB: "They face legal, emotional, and social consequences.",
        optionC: "They feel stronger and more confident.",
        optionD: "They solve their problems permanently.",
        correctOption: "B",
        order: 6,
      },
      {
        text: "According to the text, what is the most powerful weapon against violence?",
        optionA: "Physical strength.",
        optionB: "Money and influence.",
        optionC: "Education and awareness.",
        optionD: "Government control.",
        correctOption: "C",
        order: 7,
      },
      {
        text: "What does the text say young people can do to promote peace?",
        optionA: "Avoid all social interactions.",
        optionB: "Lead by example, show respect, and stand up against bullying.",
        optionC: "Only focus on their own problems.",
        optionD: "Compete with others to prove they are better.",
        correctOption: "B",
        order: 8,
      },
      {
        text: "According to the text, how does bullying relate to violence?",
        optionA: "Bullying is a harmless part of growing up.",
        optionB: "Bullying has nothing to do with violence.",
        optionC: "Bullying is a form of violence that causes lasting harm.",
        optionD: "Bullying only happens in schools.",
        correctOption: "C",
        order: 9,
      },
      {
        text: "What is the text's overall message for society?",
        optionA: "Protect yourself at all costs.",
        optionB: "Build a culture of peace, respect, and non-violence.",
        optionC: "Only strong people can stop violence.",
        optionD: "The government must solve all violent conflicts.",
        correctOption: "B",
        order: 10,
      },
    ],
  },
  {
    name: "Japan",
    slug: "japan",
    flagEmoji: "🇯🇵",
    monument: "Mount Fuji",
    order: 2,
    questions: [
      {
        text: "What does the text say is the foundation of a peaceful society?",
        optionA: "Military power and strict laws.",
        optionB: "Mutual respect and understanding among people.",
        optionC: "Economic wealth and technology.",
        optionD: "Total agreement on all issues.",
        correctOption: "B",
        order: 1,
      },
      {
        text: "According to the text, what happens when people choose dialogue over violence?",
        optionA: "They appear weak to others.",
        optionB: "Problems become harder to solve.",
        optionC: "Relationships are strengthened and solutions are found.",
        optionD: "Nothing changes in the situation.",
        correctOption: "C",
        order: 2,
      },
      {
        text: "Which value does the text highlight as essential for resolving conflicts peacefully?",
        optionA: "Pride and stubbornness.",
        optionB: "Patience and active listening.",
        optionC: "Speed and decisiveness.",
        optionD: "Competition and self-interest.",
        correctOption: "B",
        order: 3,
      },
      {
        text: "What does the text say about anger as a response to conflict?",
        optionA: "Anger is always productive and motivating.",
        optionB: "Anger should be expressed through violence.",
        optionC: "Anger is natural but must be managed with self-control.",
        optionD: "Anger has no connection to violence.",
        correctOption: "C",
        order: 4,
      },
      {
        text: "According to the text, what is one long-term effect of living in a violent environment?",
        optionA: "People become mentally stronger.",
        optionB: "Communities develop better problem-solving skills.",
        optionC: "People suffer from anxiety, fear, and emotional damage.",
        optionD: "Society learns to accept conflict as normal.",
        correctOption: "C",
        order: 5,
      },
      {
        text: "The text describes non-violence as which of the following?",
        optionA: "A sign of weakness and passivity.",
        optionB: "Only possible for trained professionals.",
        optionC: "A sign of strength, wisdom, and courage.",
        optionD: "Useful only in certain cultures.",
        correctOption: "C",
        order: 6,
      },
      {
        text: "What does the text say students should do when they witness bullying?",
        optionA: "Join in to avoid being targeted themselves.",
        optionB: "Pretend they did not see anything.",
        optionC: "Report it and support the victim.",
        optionD: "Fight the bully to defend the victim.",
        correctOption: "C",
        order: 7,
      },
      {
        text: "According to the text, what do peaceful leaders have in common?",
        optionA: "They use fear to control others.",
        optionB: "They make decisions based on personal gain.",
        optionC: "They inspire others through example and compassion.",
        optionD: "They avoid all difficult conversations.",
        correctOption: "C",
        order: 8,
      },
      {
        text: "What does the text say about forgiving someone who has hurt you?",
        optionA: "Forgiveness is impossible after violence.",
        optionB: "Forgiveness is a sign of weakness.",
        optionC: "Forgiveness is a powerful step toward healing.",
        optionD: "Forgiveness only benefits the person who caused harm.",
        correctOption: "C",
        order: 9,
      },
      {
        text: "According to the text, what should schools do to help reduce violence?",
        optionA: "Implement strict punishments for all students.",
        optionB: "Eliminate all sports and competitive activities.",
        optionC: "Teach conflict resolution, empathy, and communication skills.",
        optionD: "Separate students who disagree from each other.",
        correctOption: "C",
        order: 10,
      },
    ],
  },
  {
    name: "Italy",
    slug: "italy",
    flagEmoji: "🇮🇹",
    monument: "Colosseum, Rome",
    order: 3,
    questions: [
      {
        text: "What does the text identify as the root cause of most violent conflicts?",
        optionA: "Differences in language and culture.",
        optionB: "Poor communication, misunderstanding, and lack of empathy.",
        optionC: "Economic inequality between countries.",
        optionD: "The absence of strict laws.",
        correctOption: "B",
        order: 1,
      },
      {
        text: "According to the text, what is the difference between a disagreement and violence?",
        optionA: "There is no difference between the two.",
        optionB: "A disagreement is illegal; violence is not.",
        optionC: "A disagreement can be resolved peacefully; violence causes unnecessary harm.",
        optionD: "Disagreements only happen between friends.",
        correctOption: "C",
        order: 2,
      },
      {
        text: "The text compares peaceful communication to which of the following?",
        optionA: "A weapon used against enemies.",
        optionB: "A bridge that connects people.",
        optionC: "A wall that separates people.",
        optionD: "A competition with a winner and a loser.",
        correctOption: "B",
        order: 3,
      },
      {
        text: "According to the text, why is it important to control your emotions during a conflict?",
        optionA: "To show others that you do not care.",
        optionB: "To prevent the situation from escalating into violence.",
        optionC: "To win the argument more easily.",
        optionD: "To appear more intelligent than the other person.",
        correctOption: "B",
        order: 4,
      },
      {
        text: "What does the text say about the impact of violent media on young people?",
        optionA: "It has no real effect on their behavior.",
        optionB: "It makes young people more creative.",
        optionC: "It can normalize violence and make it seem acceptable.",
        optionD: "It teaches important life lessons about survival.",
        correctOption: "C",
        order: 5,
      },
      {
        text: "According to the text, what is one effective way to express frustration without violence?",
        optionA: "Break objects to release tension.",
        optionB: "Speak calmly about your feelings and needs.",
        optionC: "Avoid the person who made you angry permanently.",
        optionD: "Use sarcasm to make your point.",
        correctOption: "B",
        order: 6,
      },
      {
        text: "What does the text say about the relationship between respect and peace?",
        optionA: "Respect is not necessary for peace.",
        optionB: "Peace can exist without mutual respect.",
        optionC: "Respect for others is the foundation of lasting peace.",
        optionD: "Respect must be earned through strength.",
        correctOption: "C",
        order: 7,
      },
      {
        text: "According to the text, which of the following best describes a nonviolent response to injustice?",
        optionA: "Ignoring the injustice and doing nothing.",
        optionB: "Retaliating with equal or greater force.",
        optionC: "Protesting peacefully and speaking out through proper channels.",
        optionD: "Accepting injustice as a natural part of life.",
        correctOption: "C",
        order: 8,
      },
      {
        text: "What does the text say about communities that practice non-violence?",
        optionA: "They are weaker and more vulnerable.",
        optionB: "They experience more crime and disorder.",
        optionC: "They are safer, more united, and more prosperous.",
        optionD: "They have no way to protect themselves.",
        correctOption: "C",
        order: 9,
      },
      {
        text: "According to the text, what is the first step toward breaking the cycle of violence?",
        optionA: "Punishing violent individuals as severely as possible.",
        optionB: "Acknowledging that violence is never justified.",
        optionC: "Increasing police and military presence.",
        optionD: "Separating violent people from the rest of society.",
        correctOption: "B",
        order: 10,
      },
    ],
  },
  {
    name: "United States",
    slug: "united-states",
    flagEmoji: "🇺🇸",
    monument: "Statue of Liberty",
    order: 4,
    questions: [
      {
        text: "What does the text say is the most important skill for avoiding conflict?",
        optionA: "Physical strength and endurance.",
        optionB: "The ability to run away quickly.",
        optionC: "Effective communication and emotional intelligence.",
        optionD: "Having more resources than others.",
        correctOption: "C",
        order: 1,
      },
      {
        text: "According to the text, what should a person do when they feel provoked?",
        optionA: "Respond immediately with strong action.",
        optionB: "Take a pause, breathe, and think before responding.",
        optionC: "Ask a third party to respond for them.",
        optionD: "Show the other person they are not afraid.",
        correctOption: "B",
        order: 2,
      },
      {
        text: "The text describes verbal aggression as which of the following?",
        optionA: "A harmless way to express emotions.",
        optionB: "Less serious than physical violence.",
        optionC: "A form of violence that causes real emotional damage.",
        optionD: "Only harmful when it is repeated many times.",
        correctOption: "C",
        order: 3,
      },
      {
        text: "According to the text, what is the role of family in preventing violence?",
        optionA: "Families have little influence on violent behavior.",
        optionB: "Families should keep problems private and hidden.",
        optionC: "Families play a key role by modeling respect and peaceful behavior at home.",
        optionD: "Families should let children resolve their own conflicts.",
        correctOption: "C",
        order: 4,
      },
      {
        text: "What does the text say about the cycle of violence?",
        optionA: "The cycle of violence is impossible to break.",
        optionB: "It only affects people in certain countries.",
        optionC: "It is not real; violence does not repeat itself.",
        optionD: "It can be broken through conscious choice, education, and support.",
        correctOption: "D",
        order: 5,
      },
      {
        text: "According to the text, what does real courage look like?",
        optionA: "Winning every physical fight you are in.",
        optionB: "Never showing any emotions to others.",
        optionC: "Choosing peace over violence even when you feel angry.",
        optionD: "Making others fear you through strength.",
        correctOption: "C",
        order: 6,
      },
      {
        text: "What does the text say about the importance of mental health in preventing violence?",
        optionA: "Mental health has no connection to violent behavior.",
        optionB: "Only mentally ill people commit violence.",
        optionC: "Supporting mental health helps people manage emotions and reduce aggression.",
        optionD: "Mental health is a private matter that schools should not address.",
        correctOption: "C",
        order: 7,
      },
      {
        text: "According to the text, how can art and creativity help reduce violence?",
        optionA: "They cannot; only laws can reduce violence.",
        optionB: "They give people a positive outlet to express their feelings.",
        optionC: "They distract people from real problems.",
        optionD: "They are only useful for young children.",
        correctOption: "B",
        order: 8,
      },
      {
        text: "What does the text say about bystanders in violent situations?",
        optionA: "Bystanders should always intervene physically.",
        optionB: "Bystanders have no responsibility in violent situations.",
        optionC: "Bystanders can help by seeking adult assistance or calling for help.",
        optionD: "Bystanders make situations worse by getting involved.",
        correctOption: "C",
        order: 9,
      },
      {
        text: "According to the text, what does it mean to be an 'upstander'?",
        optionA: "Someone who watches violence without reacting.",
        optionB: "Someone who fights against bullies physically.",
        optionC: "Someone who speaks up and takes positive action to stop harm.",
        optionD: "Someone who reports all minor disagreements to authorities.",
        correctOption: "C",
        order: 10,
      },
    ],
  },
  {
    name: "Mexico",
    slug: "mexico",
    flagEmoji: "🇲🇽",
    monument: "Chichen Itza",
    order: 5,
    questions: [
      {
        text: "What does the text identify as a key difference between conflict and violence?",
        optionA: "Conflict is always violent; there is no difference.",
        optionB: "Violence is legal in some situations; conflict is not.",
        optionC: "Conflict is a natural part of life; violence is a harmful choice.",
        optionD: "Conflict only occurs between strangers.",
        correctOption: "C",
        order: 1,
      },
      {
        text: "According to the text, what is the first step in peaceful conflict resolution?",
        optionA: "Demanding that the other person apologize first.",
        optionB: "Listening carefully to understand the other person's perspective.",
        optionC: "Finding a judge or authority to decide who is right.",
        optionD: "Writing down all the reasons why you are correct.",
        correctOption: "B",
        order: 2,
      },
      {
        text: "The text suggests that violence often comes from which of the following?",
        optionA: "Too much education and overthinking.",
        optionB: "Unmanaged fear, insecurity, or frustration.",
        optionC: "Strong cultural traditions.",
        optionD: "Too many rules and restrictions.",
        correctOption: "B",
        order: 3,
      },
      {
        text: "According to the text, what can happen to friendships when violence is used?",
        optionA: "Friendships become stronger after violence.",
        optionB: "Friends forgive and forget very quickly.",
        optionC: "Violence permanently destroys trust and damages relationships.",
        optionD: "Friendships are not affected by violent behavior.",
        correctOption: "C",
        order: 4,
      },
      {
        text: "What does the text say about the phrase 'an eye for an eye'?",
        optionA: "It is the best way to achieve justice.",
        optionB: "It is a tradition that should be respected.",
        optionC: "It only works in certain legal systems.",
        optionD: "It leads to a never-ending cycle of revenge and more violence.",
        correctOption: "D",
        order: 5,
      },
      {
        text: "According to the text, what can students do in their school to promote a culture of peace?",
        optionA: "Compete with each other to be the best at everything.",
        optionB: "Create peaceful zones, support clubs, and conflict resolution programs.",
        optionC: "Report every small problem to the principal.",
        optionD: "Avoid talking to students who are different from them.",
        correctOption: "B",
        order: 6,
      },
      {
        text: "The text describes social media as which of the following in relation to violence?",
        optionA: "A space that only promotes positive values.",
        optionB: "A platform where cyberbullying and online violence can occur.",
        optionC: "An environment where violence has no real consequences.",
        optionD: "A tool that is never used to spread violent content.",
        correctOption: "B",
        order: 7,
      },
      {
        text: "According to the text, what is the relationship between poverty and violence?",
        optionA: "Poverty always causes violence.",
        optionB: "There is no connection between poverty and violence.",
        optionC: "Poverty can increase the risk of violence, but it is never an excuse.",
        optionD: "Violence only exists in wealthy communities.",
        correctOption: "C",
        order: 8,
      },
      {
        text: "What does the text say about the importance of saying 'no' to peer pressure?",
        optionA: "It is impossible to say no to peer pressure.",
        optionB: "Saying no is a sign of social failure.",
        optionC: "Resisting peer pressure to act violently shows strength of character.",
        optionD: "Peer pressure never leads to violent behavior.",
        correctOption: "C",
        order: 9,
      },
      {
        text: "According to the text, what is the ultimate goal of choosing non-violence?",
        optionA: "To show others that you are afraid of conflict.",
        optionB: "To avoid all difficult conversations and situations.",
        optionC: "To build a world where everyone feels safe, valued, and respected.",
        optionD: "To gain approval from authority figures.",
        correctOption: "C",
        order: 10,
      },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  for (const country of countries) {
    const { questions, ...countryData } = country;

    const created = await prisma.country.upsert({
      where: { slug: countryData.slug },
      update: countryData,
      create: countryData,
    });

    console.log(`✅ Created country: ${created.name}`);

    // Delete existing questions for this country before re-seeding
    await prisma.question.deleteMany({ where: { countryId: created.id } });

    for (const q of questions) {
      await prisma.question.create({
        data: { ...q, countryId: created.id },
      });
    }

    console.log(`   📝 ${questions.length} questions added for ${created.name}`);
  }

  console.log("\n✅ Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
